# .github/workflows/autoupdate.yml
name: Auto Update Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'log/*.csv'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update Migrations
        run: python scripts/update_migrations.py