name: Migration Workflow

on:
  workflow_dispatch:
    inputs:
      names:
        description: 'Comma-separated list of names to migrate'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      jobid: ${{ steps.setup.outputs.jobid }}
      migration_data: ${{ steps.prepare.outputs.data }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup
        id: setup
        run: |
          JOBID=$(date +%y%m%d.%H%M%S)
          echo "jobid=$JOBID" >> $GITHUB_OUTPUT
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b feature/$JOBID

      - name: Prepare Migration Data
        id: prepare
        run: |
          python scripts/prepare_migration.py \
            --names "${{ github.event.inputs.names }}" \
            --jobid "${{ steps.setup.outputs.jobid }}" > migration_data.json
          echo "data=$(cat migration_data.json)" >> $GITHUB_OUTPUT

  stage1:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/${{ needs.prepare.outputs.jobid }}
      - name: Run Stage 1
        run: |
          python scripts/run_migration.py \
            "${{ github.event.inputs.names }}" \
            "${{ needs.prepare.outputs.jobid }}" \
            "World 1-1"
      - name: Upload stage results
        uses: actions/upload-artifact@v4
        with:
          name: stage1-results-${{ needs.prepare.outputs.jobid }}
          path: log/
          retention-days: 1
      - name: Push Stage 1 Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add log/
          git commit -m "Stage 1 results for job ${{ needs.prepare.outputs.jobid }}"
          git push origin feature/${{ needs.prepare.outputs.jobid }}

  stage2:
    needs: stage1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/${{ needs.prepare.outputs.jobid }}
      - name: Download previous results
        uses: actions/download-artifact@v4
        with:
          name: stage1-results-${{ needs.prepare.outputs.jobid }}
          path: log/
      - name: Run Stage 2
        run: |
          python scripts/run_migration.py \
            "${{ github.event.inputs.names }}" \
            "${{ needs.prepare.outputs.jobid }}" \
            "World 1-2"
      - name: Upload stage results
        uses: actions/upload-artifact@v4
        with:
          name: stage2-results-${{ needs.prepare.outputs.jobid }}
          path: log/
          retention-days: 1
      - name: Push Stage 2 Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add log/
          git commit -m "Stage 2 results for job ${{ needs.prepare.outputs.jobid }}"
          git push origin feature/${{ needs.prepare.outputs.jobid }}

  stage3:
    needs: stage2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/${{ needs.prepare.outputs.jobid }}
      - name: Download previous results
        uses: actions/download-artifact@v4
        with:
          name: stage2-results-${{ needs.prepare.outputs.jobid }}
          path: log/
      - name: Run Stage 3
        run: |
          python scripts/run_migration.py \
            "${{ github.event.inputs.names }}" \
            "${{ needs.prepare.outputs.jobid }}" \
            "World 1-3"
      - name: Upload stage results
        uses: actions/upload-artifact@v4
        with:
          name: stage3-results-${{ needs.prepare.outputs.jobid }}
          path: log/
          retention-days: 1
      - name: Push Stage 3 Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add log/
          git commit -m "Stage 3 results for job ${{ needs.prepare.outputs.jobid }}"
          git push origin feature/${{ needs.prepare.outputs.jobid }}

  finalize:
    needs: [prepare, stage3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/${{ needs.prepare.outputs.jobid }}
      
      - name: Download all stage results
        uses: actions/download-artifact@v4
        with:
          path: log/

      - name: Update Results
        run: |
          python scripts/update_results.py \
            --jobid "${{ needs.prepare.outputs.jobid }}" \
            --names "${{ github.event.inputs.names }}"

      - name: Push Changes
        run: |
          git add log/
          git commit -m "Migration results for job ${{ needs.prepare.outputs.jobid }}"
          git push origin feature/${{ needs.prepare.outputs.jobid }}
          gh pr create --base main --title "Migration ${{ needs.prepare.outputs.jobid }}" --body "Migration results"